version: '3.8'
services:
  users_api:
    build:
      context: ./APIS
    ports:
      - "3001:3000"
    volumes:
      - ./APIS/users:/usr/userAPI

  orders_api:
    build:
      context: ./APIS
    ports:
      - "3002:3000"
    volumes:
      - ./APIS/orders:/usr/ordersAPI

  memberships_api:
    build:
      context: ./APIS
    ports:
      - "3003:3000"
    volumes:
      - ./APIS/memberships:/usr/membershipsAPI